name: Generate snake animation

on:
  schedule: # every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?color_snake=#e0352b&color_dots=#f3d6d6,#ffb3b3,#ff8080,#ff3b30,#e0352b
            dist/snake-dark.svg?color_snake=#ff3b30&color_dots=#2a1216,#5c1e26,#932430,#e0352b,#ff3b30

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
